# genx playbook
# sets up and configures a GenX environment on Linux

# THIS IS PURELY A TEST VERSION TO TELL YOU WHAT TO DO IT'S NOT ACTUALLY EXECUTABLE
# YET SO DON'T EVEN TRY

# Known issues:

# TODO:
# check scipy dependencies on non-Ubuntu distros
# maybe switch to debian RHEL if apt is fucked

---
- hosts: genx
  remote_user: root
  sudo: yes # make this per task maybe idk play safe for now?
  vars:
    http_port: 80
    max_clients: 200
  # remote_user: root
  tasks:
  - name: basics (git and python)
  - shell: apt-get install git python-dev

  - name:install pip
  - shell: apt-get install pip

  - name: maybe avoid this with anaconda TEST THIS ON A CLEAN BOX # TODO: make this version insensitive
  - shell: wget http://09c8d0b2229f813c1b93-c95ac804525aac4b6dba79b00b39d1d3.r79.cf1.rackcdn.com/Anaconda-1.9.1-Linux-x86_64.sh
			bash Anaconda-1.9.1-Linux-x86[_64].sh

			# NB ANACONDA HAS AN INTERACTIVE SETUP AND CAN'T BE SCRIPTED



  - name: set up the numpy/scipy prereqs (fortran compiler lol.)
  - shell: apt-get install libatlas-base-dev

  - name: add swap so that scipy can compile lol # (can't hurt for later, you can always turn off [nomfp ]).
  - shell: sudo /bin/dd if=/dev/zero of=/var/swap.1 bs=1M count=1024;
			sudo /sbin/mkswap /var/swap.1;
			sudo /sbin/swapon /var/swap.1;

  - name: actually install numpy and scipy
  - shell: apt-get install python-numpy python-scipy

  - name: set up celery
  - shell: pip install celery

  - name: set up rabbitmq-server for celery message queue parallel thing (lol erlang!!! fuck yeah)
  - shell: apt-get install rabbitmq-server

  - name: set up flower for celery web control
  - shell: pip install flower

  - name: git clone GenX repo? (or did we handle this earlier idk)
  - shell: git clone https://github.com/joshp123/cloud-meta-genx.git
  # stick it somewhere sensible

  - name: if no anaconda do flask dependencies (check website)
  - shell: echo "FLASK DEPENDENCIES NOT YET IMPLEMENTED"
  - name: check FLASK installed
  - shell: 

  - launching:
     - name: celery init
     - celery[]

     - name: flower init

     - name: test flower server? # TODO: some DNS shit maybe

